version: '3.7'

x-docker-volume:
    &docker-volume
    - /var/run/docker.sock:/var/run/docker.sock:ro

services:
    traefik:
        image: traefik:v2.2.8
        command:
            - "--api.insecure=true"
            - "--entrypoints.web.address=:80"
            - "--log.level=WARN"
            - "--providers.docker=true"
            - "--providers.docker.defaultRule=Host(`${TRAEFIK_HOST}.${DOMAIN}`)"
            - "--providers.docker.swarmMode=false"
        networks:
            - traefik
        ports:
            - "80:80"
            - "8080:8080"
        restart: always
        volumes: *docker-volume
    api:
        build:
            context: ./containers/development/api
            target: dev
        networks:
            - traefik
        volumes:
            - ./volumes/api:/home/node/app
    info:
        build:
            context: ./containers/support/info
            args:
                domain: ${DOMAIN}
        networks:
            - traefik
        volumes:
            - ./volumes/api/output:/usr/local/apache2/htdocs/api
networks:
    traefik:
