type Query {
  Postgres: Postgres
  UsernameExists(username: String!): Boolean
}

type Postgres {
  IsWorking: Boolean
}

type Mutation {
  Account: Account
}

type Account {
  Create(username: String!): Boolean
  Delete(username: String!): Boolean
}
